const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1598255462000,
      duration: 5400000,
      id: '272775522',
      name: 'Lunch&Learn: SUCCESSFUL SELLING IN TECHNOLOGY BUSINESS',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1600164000000,
      local_date: '2020-09-15',
      local_time: '12:00',
      updated: 1598255462000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
        id: 26052503,
        name: 'WERK1',
        lat: 48.12380599975586,
        lon: 11.608254432678223,
        repinned: false,
        address_1: 'Atelierstraße 29',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1458124246000,
        name: 'WERK1',
        id: 19716609,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'WERK1munich',
        who: 'movers and shakers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/WERK1munich/events/272775522/',
      description:
        'Andreas Spechtler, founder and CEO of Silicon Castles, shares practical guidance on the successful selling of your technology into B2B markets.Andreas Spechtler has more than 25 years of experience in the global technology and licensing business, digital entertainment, international marketing, sales and operations all over the world. Andreas worked for American, German and Japanese companies including Real Networks and Sony Corporation and looks back on many years of startup and incubation experience inside and outside of corporations. In his last corporate job, he was an executive at Dolby Laboratories and served as the President of Dolby Laboratories International. End 2016 he left the corporate world and in 2017 he founded Silicon Castles.Silicon Castles is a Technology Business Architect for deep technology businesses with a focus on intellectual property licensing businesses and is based in Salzburg. Silicon Castles focuses on European Diamonds i.e. technology startups with a unique business idea, outstanding intellectual property, and scalable technologies that can solve a global problem. The company Silicon Castles supports startups in various areas; from early-stage investment, set up of a global licensing model, and individual coaching to active participation in global business development and sales via the Silicon Castles global network in Europe, US, and Asia. For more details',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
};

export { mockEvents };
